apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
name: cicd-apps
rules:
  - apiGroups:
    - apps
    - extensions
    resources:  
    - deployments
    - replicasets
    verbs:  
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travis-apps
  namespace: squad-a-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-apps
subjects:
- kind: ServiceAccount
  name: travis

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-apps
  namespace: squad-b-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-apps
subjects:
- kind: ServiceAccount
  name: jenkins
